# Generated by Django 2.0.7 on 2019-12-24 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, upload_to='logoAgences', verbose_name='Logo')),
                ('nomag', models.CharField(max_length=100, unique=True, verbose_name='Agence')),
                ('dateouverture', models.DateField(verbose_name='Date Ouverture')),
                ('pays', models.CharField(max_length=150, verbose_name='Pays')),
                ('ville', models.CharField(max_length=150, verbose_name='Ville')),
                ('departement', models.CharField(max_length=150, verbose_name='Département')),
                ('province', models.CharField(max_length=150, verbose_name='Province')),
                ('quartier', models.CharField(max_length=150, verbose_name='Quartier')),
                ('telephone1', models.BigIntegerField(verbose_name='Telephone 1')),
                ('telephone2', models.BigIntegerField(verbose_name='Telephone 2')),
                ('email', models.CharField(max_length=150, verbose_name='Email')),
                ('siteweb', models.CharField(max_length=150, verbose_name='Site Web')),
                ('pincode', models.CharField(blank=True, max_length=50, verbose_name='Code Pin Agence')),
                ('is_active', models.BooleanField(default=True, verbose_name='Agence active ?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('gerant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Gerant_Agence', to=settings.AUTH_USER_MODEL, verbose_name='Gérant')),
            ],
            options={
                'verbose_name_plural': 'Les Agences',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noms', models.CharField(max_length=200, verbose_name='Noms')),
                ('prenoms', models.CharField(max_length=200, verbose_name='Prénoms')),
                ('email', models.EmailField(max_length=255, null=True, verbose_name='Email')),
                ('datenaiss', models.DateField(verbose_name='Date de Naissance')),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=10, verbose_name='Sexe')),
                ('profession', models.CharField(max_length=200, verbose_name='Profession')),
                ('revenu_annuel', models.BigIntegerField(null=True, verbose_name='Revenu Annuel')),
                ('pays', models.CharField(max_length=150, verbose_name='Pays')),
                ('ville', models.CharField(max_length=150, verbose_name='Ville')),
                ('departement', models.CharField(max_length=150, verbose_name='Département')),
                ('province', models.CharField(max_length=150, verbose_name='Province')),
                ('quartier', models.CharField(max_length=150, verbose_name='Quartier')),
                ('mobile', models.CharField(max_length=20, null=True, verbose_name='Mobile')),
                ('pincode', models.CharField(blank=True, max_length=50, verbose_name='Code Pin Agence')),
                ('photo', models.ImageField(null=True, upload_to='static/images/users', verbose_name='Photo')),
                ('signature', models.ImageField(null=True, upload_to='static/images/signatures', verbose_name='Signature')),
                ('is_active', models.BooleanField(default=True, verbose_name='Client Actif ?')),
                ('status', models.CharField(choices=[('Non attribué', 'Non attribué'), ('Attribué', 'Attribué')], max_length=150, null=True, verbose_name='Statut Client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('agence', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_choisi', to='microfinance.Agence', verbose_name='Agence')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Membres',
            },
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250, verbose_name='Numéro Général')),
                ('ouverture', models.DateField(verbose_name='Ouverture')),
                ('cloture', models.DateField(verbose_name='Clôture')),
                ('intitule', models.CharField(blank=True, max_length=250, null=True, verbose_name='Intitulé')),
                ('statut', models.CharField(choices=[('En Activité', 'En Activité'), ('En Arrêt', 'En Arrêt')], default='En Activité', max_length=130, verbose_name='Statut du Compte')),
                ('matricule', models.CharField(max_length=250, verbose_name='Matricule Fonctionnaire')),
                ('montancartone', models.FloatField(verbose_name='Montant Cartoné')),
                ('numcpte', models.CharField(max_length=250, verbose_name='Compte Intérêts')),
                ('decouvertauto', models.FloatField(verbose_name='Découvert Autorisé')),
                ('debut', models.DateField(verbose_name='Début')),
                ('fin', models.DateField(max_length=250, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('agence', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_compte', to='microfinance.Agence', verbose_name='Agence')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_compte', to='microfinance.Client', verbose_name='Titulaire du Compte')),
                ('gestionnaire', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_compte', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='TypeCompte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(blank=True, max_length=50, verbose_name='Code Pin Type Compte')),
                ('libelle', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'Les Types de Compte',
            },
        ),
        migrations.AddField(
            model_name='compte',
            name='typecompte',
            field=models.ForeignKey(blank=True, null=True, on_delete='cascade', to='microfinance.TypeCompte', verbose_name='Nature du Compte'),
        ),
    ]
