# Generated by Django 2.0.7 on 2019-12-24 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('microfinance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=250, verbose_name='Numéro de Caisse')),
                ('solde', models.FloatField(verbose_name='Solde')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
            ],
            options={
                'verbose_name_plural': 'La Caisse Principale',
            },
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(blank=True, max_length=50, verbose_name='Code Pin Depot')),
                ('montantverse', models.FloatField(verbose_name='Montant Versé')),
                ('motif', models.CharField(blank=True, max_length=250, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('agence', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_depot', to='microfinance.Agence', verbose_name='Agence')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_depot', to='microfinance.Client', verbose_name='Client')),
                ('numcpte', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_depot', to='microfinance.Compte', verbose_name='N°/Cpte')),
            ],
            options={
                'verbose_name_plural': 'Dépôts',
            },
        ),
        migrations.CreateModel(
            name='Retrait',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(blank=True, max_length=50, verbose_name='Code Pin Retrait')),
                ('montantretire', models.FloatField(verbose_name='Montant Retiré')),
                ('motif', models.CharField(blank=True, max_length=250, verbose_name='Motif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de Modification')),
                ('agence', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='agence_retrait', to='microfinance.Agence', verbose_name='Agence')),
                ('ajoute_par', models.ForeignKey(blank=True, editable=False, null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('client', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_retrai', to='microfinance.Client', verbose_name='Client')),
                ('compte', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_retrai', to='microfinance.Compte', verbose_name='N°/Cpte')),
            ],
            options={
                'verbose_name_plural': 'Retraits',
            },
        ),
    ]
