# Generated by Django 2.1.5 on 2019-12-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0003_auto_20191226_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrait',
            name='motif',
            field=models.TextField(blank=True, max_length=250, verbose_name='Motif'),
        ),
    ]
