# Generated by Django 2.1.5 on 2019-12-26 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microfinance', '0004_auto_20191226_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrait',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_retrait', to='microfinance.Client', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='retrait',
            name='compte',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='compte_retrait', to='microfinance.Compte', verbose_name='N°/Cpte'),
        ),
    ]
